/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author Andrea
 */
public class ActualizarPokemon extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaMedallas
     */
    public ActualizarPokemon() {
       initComponents();
       
    }

   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtAgregar = new javax.swing.JButton();
        txtMenu = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtConsultar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtModificar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtEliminar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 410));
        setPreferredSize(new java.awt.Dimension(710, 410));
        getContentPane().setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(280, 230, 50, 60);

        txtAgregar.setBackground(java.awt.Color.orange);
        txtAgregar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtAgregar.setForeground(new java.awt.Color(102, 62, 0));
        txtAgregar.setText("Agregar");
        txtAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtAgregarMouseClicked(evt);
            }
        });
        getContentPane().add(txtAgregar);
        txtAgregar.setBounds(300, 190, 100, 27);

        txtMenu.setBackground(java.awt.Color.orange);
        txtMenu.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtMenu.setForeground(new java.awt.Color(102, 62, 0));
        txtMenu.setText("Menú");
        txtMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMenuMouseClicked(evt);
            }
        });
        getContentPane().add(txtMenu);
        txtMenu.setBounds(260, 290, 80, 27);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonModificar.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 130, 60, 60);

        txtConsultar.setBackground(java.awt.Color.orange);
        txtConsultar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtConsultar.setForeground(new java.awt.Color(102, 62, 0));
        txtConsultar.setText("Consultar");
        txtConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtConsultarMouseClicked(evt);
            }
        });
        getContentPane().add(txtConsultar);
        txtConsultar.setBounds(50, 190, 100, 27);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonConsultar.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 130, 60, 60);

        txtModificar.setBackground(java.awt.Color.orange);
        txtModificar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtModificar.setForeground(new java.awt.Color(102, 62, 0));
        txtModificar.setText("Modificar");
        txtModificar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtModificarMouseClicked(evt);
            }
        });
        txtModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModificarActionPerformed(evt);
            }
        });
        getContentPane().add(txtModificar);
        txtModificar.setBounds(180, 190, 100, 27);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonAgregar.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(330, 130, 50, 60);

        txtEliminar.setBackground(java.awt.Color.orange);
        txtEliminar.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        txtEliminar.setForeground(new java.awt.Color(102, 62, 0));
        txtEliminar.setText("Eliminar");
        txtEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEliminarMouseClicked(evt);
            }
        });
        getContentPane().add(txtEliminar);
        txtEliminar.setBounds(110, 290, 100, 27);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonEliminar.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(140, 230, 50, 60);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/22.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 110, 410, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/02ActualizarPokemon.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 690, 367);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModificarActionPerformed

    private void txtConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtConsultarMouseClicked
        // TODO add your handling code here:
        ConsultarPokemon consPokemon= new ConsultarPokemon();
        consPokemon.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtConsultarMouseClicked

    private void txtModificarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtModificarMouseClicked
        // TODO add your handling code here:
        ModificarPokemon modPoke= new ModificarPokemon();
        modPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtModificarMouseClicked

    private void txtAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtAgregarMouseClicked
        // TODO add your handling code here:
        InsertarPokemon insPoke= new InsertarPokemon();
        insPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtAgregarMouseClicked

    private void txtEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEliminarMouseClicked
        // TODO add your handling code here:
        EliminarPokemon elimPoke= new EliminarPokemon();
        elimPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtEliminarMouseClicked

    private void txtMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal= new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_txtMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ActualizarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ActualizarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ActualizarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ActualizarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ActualizarPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton txtAgregar;
    private javax.swing.JButton txtConsultar;
    private javax.swing.JButton txtEliminar;
    private javax.swing.JButton txtMenu;
    private javax.swing.JButton txtModificar;
    // End of variables declaration//GEN-END:variables
}
