/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Combo;
import Clases.Procedimientos;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Andrea
 */
public class AsignarPokemonEntrenado extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaMedallas
     */
    public AsignarPokemonEntrenado() {
       initComponents();
       Combo llenar = new Combo();       
      llenar.llenar_combo(cmbEntrenador,"SELECT * FROM EntrenadorNombre","idEntrenador","Nombre Completo");
      llenar.llenar_combo(cmbPokemon,"SELECT * FROM Pokemon","idPokemon","Nombre");
      LlenarTabla();
      this.setLocationRelativeTo(null);
       
    }
    public void LlenarTabla(){
      try
       {           
            DefaultTableModel consulta;
            consulta=Procedimientos.consultarAsfignarEntrenador(); 
            if(consulta != null){              
             jTableEntrenador.setModel(consulta);
            }else{
               JOptionPane.showMessageDialog(null, "No se encontro resultados", "Error de conexion", JOptionPane.INFORMATION_MESSAGE);
            }            
        }
        catch (SQLException e)
        {
            JOptionPane.showMessageDialog(null,"Error " + e.getMessage(), "Error de conexion", JOptionPane.ERROR_MESSAGE);
        } 
    
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableEntrenador = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbEntrenador = new javax.swing.JComboBox<>();
        cmbPokemon = new javax.swing.JComboBox<>();
        btnAsignar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(715, 410));
        setPreferredSize(new java.awt.Dimension(715, 410));
        getContentPane().setLayout(null);

        jTableEntrenador.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableEntrenador);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 130, 240, 170);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel2.setText("Entrenador:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(60, 50, 100, 21);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel3.setText("Pokemon:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 90, 100, 21);

        cmbEntrenador.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cmbEntrenador.setInheritsPopupMenu(true);
        cmbEntrenador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbEntrenadorActionPerformed(evt);
            }
        });
        getContentPane().add(cmbEntrenador);
        cmbEntrenador.setBounds(170, 40, 170, 30);

        cmbPokemon.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cmbPokemon.setInheritsPopupMenu(true);
        cmbPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(cmbPokemon);
        cmbPokemon.setBounds(170, 80, 170, 30);

        btnAsignar.setBackground(java.awt.Color.orange);
        btnAsignar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAsignar.setForeground(new java.awt.Color(102, 62, 0));
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAsignar);
        btnAsignar.setBounds(330, 190, 80, 25);

        btnMenu.setBackground(java.awt.Color.orange);
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(102, 62, 0));
        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(330, 280, 80, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(350, 220, 50, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonAsignar.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 130, 50, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 260, 200);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/248-mega_1.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(490, 90, 190, 240);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/14AsignarPokemonEntrenador.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal= new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnMenuMouseClicked

    private void cmbEntrenadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbEntrenadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbEntrenadorActionPerformed

    private void cmbPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPokemonActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
       String mensaje;
       int entrenador;
       int pokemon;   

       if(cmbEntrenador.getSelectedIndex()==0||cmbPokemon.getSelectedIndex()==0){   
           JOptionPane.showMessageDialog(null, "Favor de llenar todos los datos", "Error de introduccion de datos", JOptionPane.ERROR_MESSAGE);       
        } else{
            try{                
        pokemon =  cmbPokemon.getItemAt(cmbPokemon.getSelectedIndex()).getCodigo();
        entrenador =cmbEntrenador.getItemAt(cmbEntrenador.getSelectedIndex()).getCodigo();        
        mensaje=Procedimientos.AsignarPokemonEntrenador(entrenador,pokemon);
        JOptionPane.showMessageDialog(null, mensaje);
        cmbPokemon.setSelectedIndex(0);
        cmbEntrenador.setSelectedIndex(0); 
        LlenarTabla();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage(), "Error de conexion", JOptionPane.ERROR_MESSAGE);
            }
       } 

    }//GEN-LAST:event_btnAsignarActionPerformed

   

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AsignarPokemonEntrenado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AsignarPokemonEntrenado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AsignarPokemonEntrenado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AsignarPokemonEntrenado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AsignarPokemonEntrenado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<Combo> cmbEntrenador;
    private javax.swing.JComboBox<Combo> cmbPokemon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableEntrenador;
    // End of variables declaration//GEN-END:variables
}
