/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Conexiones;
import Clases.Procedimientos;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import Clases.Combo;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;

/**
 *
 * @author Andrea
 */
public class InsertarPokemon extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaMedallas
     */
    public InsertarPokemon() {
       initComponents();             
       Combo llenar = new Combo();       
       llenar.llenar_combo(cmbTipo,"Select * from TipoPokemon","IdTipoPoke","nombre");
    }
    
    
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtFNombre = new javax.swing.JTextField();
        txtFPreEvolucion = new javax.swing.JTextField();
        txtFEvolucion = new javax.swing.JTextField();
        txtFAltura = new javax.swing.JTextField();
        txtFPeso = new javax.swing.JTextField();
        txtFPs = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(715, 410));
        setPreferredSize(new java.awt.Dimension(715, 410));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(420, 70, 80, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("PreEvolución:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(420, 110, 80, 20);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Evolución:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(420, 150, 80, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Altura:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(420, 190, 80, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Peso:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 230, 80, 20);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("Tipo:");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(420, 310, 80, 20);

        txtFNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFNombre);
        txtFNombre.setBounds(510, 60, 170, 30);

        txtFPreEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFPreEvolucion);
        txtFPreEvolucion.setBounds(510, 100, 170, 30);

        txtFEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFEvolucion);
        txtFEvolucion.setBounds(510, 140, 170, 30);

        txtFAltura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFAltura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFAlturaActionPerformed(evt);
            }
        });
        txtFAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFAlturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtFAltura);
        txtFAltura.setBounds(510, 180, 170, 30);

        txtFPeso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPesoActionPerformed(evt);
            }
        });
        txtFPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPesoKeyTyped(evt);
            }
        });
        getContentPane().add(txtFPeso);
        txtFPeso.setBounds(510, 220, 170, 30);

        txtFPs.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFPsActionPerformed(evt);
            }
        });
        txtFPs.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFPsKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPsKeyTyped(evt);
            }
        });
        getContentPane().add(txtFPs);
        txtFPs.setBounds(510, 260, 170, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("PS:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(420, 270, 80, 20);

        cmbTipo.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cmbTipo.setInheritsPopupMenu(true);
        cmbTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(510, 310, 170, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(410, 50, 280, 310);

        btnAgregar.setBackground(java.awt.Color.orange);
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(310, 140, 90, 25);

        btnMenu.setBackground(java.awt.Color.orange);
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(310, 230, 90, 25);

        btnRegresar.setBackground(java.awt.Color.orange);
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(310, 330, 90, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonAgregar.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(330, 80, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(330, 170, 50, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonRegresar.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(330, 270, 50, 50);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/1443107685_tumblr_static_bq0z0ouo9i8g8g4cgo88kogs0 (1).gif"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 10, 280, 350);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/03AgregarPokemon.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFAlturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFAlturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFAlturaActionPerformed

    private void txtFPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPesoActionPerformed

    private void txtFPsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFPsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPsActionPerformed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal= new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        ActualizarPokemon actPoke= new ActualizarPokemon();
        actPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
       String nombre;
       String preevolucion;
       String evolucion;
       float altura;
       int peso;
       int tipo;
       int ps;
       String mensaje;
       DecimalFormat df = new DecimalFormat("#######.##");
    

       if(txtFNombre.getText().isEmpty() || txtFPreEvolucion.getText().isEmpty() || txtFEvolucion.getText().isEmpty() || txtFAltura.getText().isEmpty() || txtFPs.getText().isEmpty() || txtFPeso.getText().isEmpty() ||
          cmbTipo.getSelectedIndex()==0){   
           JOptionPane.showMessageDialog(null, "Favor de llenar todos los datos", "Error de introduccion de datos", JOptionPane.ERROR_MESSAGE);       
        } else{
            try{                
        nombre = txtFNombre.getText().trim();
        preevolucion = txtFPreEvolucion.getText().trim();
        evolucion = txtFEvolucion.getText().trim();        
        altura =  Float.parseFloat(df.format( Float.parseFloat(txtFAltura.getText().trim())));
        peso = Integer.parseInt(txtFPeso.getText().trim());
        ps = Integer.parseInt(txtFPs.getText().trim());
        tipo =cmbTipo.getItemAt(cmbTipo.getSelectedIndex()).getCodigo();        
        mensaje=Procedimientos.AgregarPokemon(nombre,preevolucion,evolucion,altura,peso,tipo,ps);
        JOptionPane.showMessageDialog(null, mensaje);
        txtFNombre.setText("");
        txtFAltura.setText("");
        txtFPeso.setText("");
        txtFPreEvolucion.setText("");
        txtFEvolucion.setText("");
        txtFPs.setText("");
        cmbTipo.setSelectedIndex(0);
        
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage(), "Error de conexion", JOptionPane.ERROR_MESSAGE);
            }
       }  
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtFAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAlturaKeyTyped
     Procedimientos.txtNumeroKeyTyped(evt,txtFAltura);
    }//GEN-LAST:event_txtFAlturaKeyTyped

    private void txtFPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPesoKeyTyped
     Procedimientos.txtNumeroKeyTyped(evt,txtFPeso);
    }//GEN-LAST:event_txtFPesoKeyTyped

    private void txtFPsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPsKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFPsKeyPressed

    private void txtFPsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPsKeyTyped
      Procedimientos.txtNumeroKeyTyped(evt,txtFPs);
    }//GEN-LAST:event_txtFPsKeyTyped

    private void cmbTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

 

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Combo> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtFAltura;
    private javax.swing.JTextField txtFEvolucion;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFPeso;
    private javax.swing.JTextField txtFPreEvolucion;
    private javax.swing.JTextField txtFPs;
    // End of variables declaration//GEN-END:variables
}
