/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author LIVERPOOL
 */
public class InsertarMedalla extends javax.swing.JFrame {

    /**
     * Creates new form InsertarMedalla
     */
    public InsertarMedalla() {
        initComponents();
           this.setResizable(false);	
             //Que aparezca en medio
	     this.setLocationRelativeTo(null);      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnLider = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        btnEntrenador = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        chBoxEntrenador = new javax.swing.JComboBox<>();
        chBoxLider = new javax.swing.JComboBox<>();
        chBoxMedalla = new javax.swing.JComboBox<>();
        tctFGimnasio = new javax.swing.JTextField();
        tctFBatalla = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(710, 410));
        setPreferredSize(new java.awt.Dimension(710, 410));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Seleccione quien recibira la medalla:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(60, 10, 310, 40);

        btnLider.setBackground(java.awt.Color.orange);
        btnLider.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnLider.setForeground(new java.awt.Color(102, 62, 0));
        btnLider.setText("Lider");
        getContentPane().add(btnLider);
        btnLider.setBounds(100, 60, 73, 23);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Entrenador:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 120, 80, 20);

        btnEntrenador.setBackground(java.awt.Color.orange);
        btnEntrenador.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        btnEntrenador.setForeground(new java.awt.Color(102, 62, 0));
        btnEntrenador.setText("Entrenador");
        getContentPane().add(btnEntrenador);
        btnEntrenador.setBounds(200, 60, 110, 23);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Medallas:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(60, 180, 80, 20);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel5.setText("Lider:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 150, 50, 20);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Gimnasio:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(60, 210, 80, 20);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Batalla:");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(60, 240, 60, 20);

        chBoxEntrenador.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(chBoxEntrenador);
        chBoxEntrenador.setBounds(170, 120, 180, 22);

        chBoxLider.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(chBoxLider);
        chBoxLider.setBounds(170, 150, 180, 22);

        chBoxMedalla.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(chBoxMedalla);
        chBoxMedalla.setBounds(170, 180, 180, 22);

        tctFGimnasio.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(tctFGimnasio);
        tctFGimnasio.setBounds(170, 210, 180, 20);

        tctFBatalla.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        getContentPane().add(tctFBatalla);
        tctFBatalla.setBounds(170, 240, 180, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 360, 160);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 10, 360, 90);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonAgregar.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(80, 280, 50, 50);

        btnAgregar.setBackground(java.awt.Color.orange);
        btnAgregar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(102, 62, 0));
        btnAgregar.setText("Agregar");
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(60, 340, 90, 25);

        btnMenu.setBackground(java.awt.Color.orange);
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(102, 62, 0));
        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(190, 340, 80, 25);

        btnRegresar.setBackground(java.awt.Color.orange);
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 62, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(300, 340, 90, 25);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(210, 280, 50, 50);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonRegresar.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(320, 280, 50, 50);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/924717_b227c45dda194b719321004cd9105625_mv2 (1).gif"))); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(440, 70, 240, 280);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/22AgregarMedallas.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal= new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        InterfazActualizarMedalla actMed= new InterfazActualizarMedalla();
        actMed.setVisible(true);
        this.dispose();
      
    }//GEN-LAST:event_btnRegresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InsertarMedalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InsertarMedalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InsertarMedalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InsertarMedalla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InsertarMedalla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEntrenador;
    private javax.swing.JButton btnLider;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<String> chBoxEntrenador;
    private javax.swing.JComboBox<String> chBoxLider;
    private javax.swing.JComboBox<String> chBoxMedalla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField tctFBatalla;
    private javax.swing.JTextField tctFGimnasio;
    // End of variables declaration//GEN-END:variables
}
