/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import Clases.Combo;
import Clases.Procedimientos;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Andrea
 */
public class ModificarPokemon extends javax.swing.JFrame {

    /**
     * Creates new form ConsultaMedallas
     */
    public ModificarPokemon() {
        initComponents();
           this.setResizable(false);	
             //Que aparezca en medio
	     this.setLocationRelativeTo(null);
        Combo llenar = new Combo();
        llenar.llenar_combo(cmbTipo, "Select * from TipoPokemon", "IdTipoPoke", "nombre");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField8 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtFIdPokemon = new javax.swing.JTextField();
        txtFNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtFPreEvolucion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtFEvolucion = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        txtFPs = new javax.swing.JTextField();
        txtFAltura = new javax.swing.JTextField();
        txtFPeso = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(720, 410));
        setPreferredSize(new java.awt.Dimension(720, 410));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 80, 70, 30);

        txtFIdPokemon.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFIdPokemon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFIdPokemonActionPerformed(evt);
            }
        });
        getContentPane().add(txtFIdPokemon);
        txtFIdPokemon.setBounds(120, 20, 170, 30);

        txtFNombre.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFNombre);
        txtFNombre.setBounds(120, 80, 170, 30);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel4.setText("idPokemon:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 20, 70, 30);

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel5.setText("PreEvolucion:");
        jLabel5.setToolTipText("");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 120, 90, 30);

        txtFPreEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFPreEvolucion);
        txtFPreEvolucion.setBounds(120, 120, 170, 30);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel6.setText("Evolucion:");
        jLabel6.setToolTipText("");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 160, 70, 30);

        txtFEvolucion.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFEvolucion);
        txtFEvolucion.setBounds(120, 160, 170, 30);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel7.setText("Altura:");
        jLabel7.setToolTipText("");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(30, 200, 70, 30);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel8.setText("Peso:");
        jLabel8.setToolTipText("");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 240, 70, 30);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel9.setText("PS:");
        jLabel9.setToolTipText("");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 280, 30, 30);

        cmbTipo.setFont(new java.awt.Font("Century Gothic", 1, 11)); // NOI18N
        cmbTipo.setInheritsPopupMenu(true);
        getContentPane().add(cmbTipo);
        cmbTipo.setBounds(120, 320, 170, 30);

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel15.setText("Tipo:");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(30, 320, 80, 20);

        txtFPs.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        getContentPane().add(txtFPs);
        txtFPs.setBounds(120, 280, 170, 30);

        txtFAltura.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFAltura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFAlturaKeyTyped(evt);
            }
        });
        getContentPane().add(txtFAltura);
        txtFAltura.setBounds(120, 200, 170, 30);

        txtFPeso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        txtFPeso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFPesoKeyTyped(evt);
            }
        });
        getContentPane().add(txtFPeso);
        txtFPeso.setBounds(120, 240, 170, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/panel1.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 70, 290, 280);

        btnBuscar.setBackground(java.awt.Color.orange);
        btnBuscar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(102, 62, 0));
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(320, 50, 80, 23);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonBuscar.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 0, 40, 50);

        btnModificar.setBackground(java.awt.Color.orange);
        btnModificar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(102, 62, 0));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });
        getContentPane().add(btnModificar);
        btnModificar.setBounds(320, 140, 90, 23);

        btnRegresar.setBackground(java.awt.Color.orange);
        btnRegresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(102, 62, 0));
        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegresar);
        btnRegresar.setBounds(320, 330, 90, 23);

        btnMenu.setBackground(java.awt.Color.orange);
        btnMenu.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(102, 62, 0));
        btnMenu.setText("Menú");
        btnMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMenuMouseClicked(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(320, 240, 90, 23);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonModificar.png"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 80, 50, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonMenu.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(340, 180, 50, 60);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/BotonRegresar.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(340, 270, 50, 60);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/924717_32abc0dac1d24096b71d7ffee2857071_mv2 (1).gif"))); // NOI18N
        getContentPane().add(jLabel14);
        jLabel14.setBounds(440, 60, 260, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/04ModificarPokemon.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 700, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtFIdPokemonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFIdPokemonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFIdPokemonActionPerformed

    private void btnMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMenuMouseClicked
        // TODO add your handling code here:
        PantallaPrincipal pantPrincipal = new PantallaPrincipal();
        pantPrincipal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuMouseClicked

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        ActualizarPokemon actPoke = new ActualizarPokemon();
        actPoke.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String vDato = txtFIdPokemon.getText().trim(); 
        if (vDato.equals("")) {
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los datos", "Error de introduccion de datos", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String sql = "SELECT * ,TipoPokemon.Nombre AS nombreTipo \n"
                        + "FROM Pokemon\n"
                        + "INNER JOIN TipoPokemon\n"
                        + "ON Pokemon.IdTipoPoke = TipoPokemon.IdTipoPoke where Pokemon.idPokemon = '" + vDato + "'";
                ResultSet consulta = Procedimientos.BuscarConsultas(sql);
                if (consulta != null && consulta.next()) {
                        txtFIdPokemon.setText(consulta.getString("idPokemon"));
                        txtFNombre.setText(consulta.getString("nombre"));
                        txtFAltura.setText(String.valueOf(consulta.getFloat("altura")));
                        txtFPeso.setText(String.valueOf(consulta.getFloat("peso")));
                        txtFPreEvolucion.setText(consulta.getString("preevolucion"));
                        txtFEvolucion.setText(consulta.getString("evolucion"));
                        txtFPs.setText(String.valueOf(consulta.getInt("ps")));
                        cmbTipo.setSelectedIndex(consulta.getInt("idTipoPoke"));
                    
                }else{
                 JOptionPane.showMessageDialog(null, "No se encontro resultados", "Error de conexion", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage(), "Error de conexion", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        int idPokemon;
        String nombre;
        String preevolucion;
        String evolucion;
        float altura;
        float peso;
        int tipo;
        int ps;
        String mensaje;

        if (txtFIdPokemon.getText().isEmpty() || txtFNombre.getText().isEmpty() || txtFPreEvolucion.getText().isEmpty() || txtFEvolucion.getText().isEmpty() || txtFAltura.getText().isEmpty() || txtFPs.getText().isEmpty() || txtFPeso.getText().isEmpty()
                || cmbTipo.getSelectedIndex() == 0 || cmbTipo.getSelectedItem().equals("Seleccionar")) {
            JOptionPane.showMessageDialog(null, "Favor de llenar todos los datos", "Error de introduccion de datos", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                idPokemon = Integer.parseInt(txtFIdPokemon.getText().trim());
                nombre = txtFNombre.getText().trim();
                preevolucion = txtFPreEvolucion.getText().trim();
                evolucion = txtFEvolucion.getText().trim();
                altura = Float.parseFloat(txtFAltura.getText().trim());
                peso = Float.parseFloat(txtFPeso.getText().trim());
                ps = Integer.parseInt(txtFPs.getText().trim());
                tipo = cmbTipo.getItemAt(cmbTipo.getSelectedIndex()).getCodigo();
                mensaje = Procedimientos.ModificarPokemon(idPokemon, nombre, preevolucion, evolucion, altura, peso, tipo, ps);
                JOptionPane.showMessageDialog(null, mensaje);
                txtFIdPokemon.setText("");
                txtFNombre.setText("");
                txtFAltura.setText("");
                txtFPeso.setText("");
                txtFPreEvolucion.setText("");
                txtFEvolucion.setText("");
                txtFPs.setText("");
                cmbTipo.setSelectedIndex(0);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "ERROR " + e.getMessage(), "Error de conexion", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void txtFAlturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFAlturaKeyTyped
        Procedimientos.txtNumeroKeyTyped(evt,txtFAltura);
    }//GEN-LAST:event_txtFAlturaKeyTyped

    private void txtFPesoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFPesoKeyTyped
      Procedimientos.txtNumeroKeyTyped(evt,txtFPeso);
    }//GEN-LAST:event_txtFPesoKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarPokemon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarPokemon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JComboBox<Combo> cmbTipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField txtFAltura;
    private javax.swing.JTextField txtFEvolucion;
    private javax.swing.JTextField txtFIdPokemon;
    private javax.swing.JTextField txtFNombre;
    private javax.swing.JTextField txtFPeso;
    private javax.swing.JTextField txtFPreEvolucion;
    private javax.swing.JTextField txtFPs;
    // End of variables declaration//GEN-END:variables
}
